### ISSUE TITLE
编译报错 log/log.go:58: assignment copies lock value to lock: sync.RWMutex

### ISSUE THREAD

**Issue by meadowair** [arxanchain/sdk-go-common#18]

**Comment by genggjh** [comment]
pls try go 1.8.1 or above to compile.

**Comment by meadowair** [comment]
安装 golang-1.9 后编译报错 
The following files contain goimports errors
log/grpclogger.go log/log.go rest/api/api_test.go
The goimports command must be run for these files

**Comment by genggjh** [comment]
pls check your GOPATH env

**Comment by genggjh** [comment]
The sdk-go-common should be under the $GOPAH/src/github.com/arxanchain/ before you run the makefile. Or try this "go get github.com/arxanchain/sdk-go-common/..."

**Comment by meadowair** [comment]
使用 go get github.com/arxanchain/sdk-go-common 重新获取项目后编译通过。
