### ISSUE TITLE
make failed on windows10

### ISSUE THREAD

**Issue by zhazhalaila** [arxanchain/sdk-go-common#44]
Go version
`go version go1.10.3 windows/amd64`
Compiler tool
`mingw-w64`
When i locate in `src\github.com\arxanchain\sdk-go-common\crypto\tools\library`， I excute make command， I get an error:

> process_begin: CreateProcess(NULL, uname, ...) failed.
   "build/utils.so"
    go build -buildmode=c-shared -o build/utils.so ./utils.go
    # runtime/cgo
    In file included from C:/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/x86_64-w64-mingw32/include/stddef.h:7,
                 from C:/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/stddef.h:1,
                 from C:\MinGW\include/stdlib.h:55,
                 from _cgo_export.c:2:
C:/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/x86_64-w64-mingw32/include/crtdefs.h:35:18: error: expected ';' before 'typedef'
 __MINGW_EXTENSION typedef unsigned __int64 size_t;
                  ^~~~~~~~
                  ;
C:/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/x86_64-w64-mingw32/include/crtdefs.h:45:18: error: expected ';' before 'typedef'
 __MINGW_EXTENSION typedef __int64 ssize_t;
                  ^~~~~~~~
                  ;
C:/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/x86_64-w64-mingw32/include/crtdefs.h:62:18: error: expected ';' before 'typedef'
 __MINGW_EXTENSION typedef __int64 intptr_t;
                  ^~~~~~~~
                  ;
C:/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/x86_64-w64-mingw32/include/crtdefs.h:75:18: error: expected ';' before 'typedef'
 __MINGW_EXTENSION typedef unsigned __int64 uintptr_t;
                  ^~~~~~~~
                  ;
C:/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/x86_64-w64-mingw32/include/crtdefs.h:88:18: error: expected ';' before 'typedef'
 __MINGW_EXTENSION typedef __int64 ptrdiff_t;
                  ^~~~~~~~
                  ;
C:/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/x86_64-w64-mingw32/include/crtdefs.h:123:18: error: expected ';' before 'typedef'
 __MINGW_EXTENSION typedef __int64 __time64_t;
                  ^~~~~~~~
                  ;
Makefile:41: recipe for target 'build/utils.so' failed
make: *** [build/utils.so] Error 2

I open build and -p folder, are empty.

**Comment by phantomSuying** [comment]
我也是这样，lz解决了吗

**Comment by zhazhalaila** [comment]
@phantomSuying  没有0.0

**Comment by ewangplay** [comment]
@zhazhalaila @phantomSuying 首先感谢你们反馈的问题，然后我们再讨论一下该问题的解决方案。

因为Go语言是跨平台的语言，理论上SDK提供的程序在windows下是可以运行的。但是，我们开发人员的开发测试环境一直是mac和linux系统，没有在任何windows系统下做过相关的开发测试工作，所以在windows系统下出现上述问题是可能的。

我们推荐使用SDK的开发人员使用mac或者linux系统，正是出于以上的原因。

如果你们坚持在windows系统下开发程序，我们提供的建议是你们可以去尝试解决这类兼容性问题。基于Go语言跨平台的特性，解决这样的问题应该是不算困难的。

我们非常鼓励外部的开发人员贡献代码和修复Bug，而且后续社区会对这种贡献提供一定的奖励方案。

在解决问题的过程中，你们可以跟我们的开发人员去交流，一起去探讨解决方案，我们的开发人员非常乐意跟你们交流，共同成长，非常感谢。
